In [1]:
import pandas as pd
import numpy as np

In [2]:
from math import radians, sin, cos, sqrt, atan2
from math import radians, cos, sin, asin, sqrt
from scipy.spatial import cKDTree
def haversine_cbd(row):
    # Radius of Earth in kilometers (use 3956 for miles)
    R = 6371.0
    lat1 = row["LATITUDE"]
    lon1 = row["LONGITUDE"]
    ## Raffles Place Lat and Long
    lat2 = 1.2830
    lon2 = 103.8513
    # Convert latitude and longitude from degrees to radians
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    
    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    # Distance in kilometers
    distance = R * c
    return distance

# This portion is used to determine the straightline distance to CBD.

In [3]:
HDB_all_info = pd.read_csv("HDB_Distance_To_CBD.csv", index_col =  False)
HDB_Resale_Price = pd.read_csv("Resale flat prices based on registration date from Jan-2017 onwards.csv")

In [4]:
len(HDB_Resale_Price)

192066

In [5]:
merged_df = pd.merge(HDB_Resale_Price, HDB_all_info, on=['block', 'street_name'], how='left')

In [6]:
df = merged_df.drop(columns=['bldg_contract_town','total_dwelling_units','1room_sold','2room_sold','3room_sold','4room_sold','5room_sold','exec_sold','multigen_sold','studio_apartment_sold','1room_rental','2room_rental','3room_rental','other_room_rental','year_completed','max_floor_lvl'])

In [7]:
df["Distance_CBD"] = df.apply(haversine_cbd, axis =1)

In [8]:
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,...,commercial,market_hawker,miscellaneous,multistorey_carpark,precinct_pavilion,LATITUDE,LONGITUDE,POSTAL,time_cbd,Distance_CBD
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,...,N,N,N,N,N,1.362005,103.853880,560406,1919,8.789584
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,...,Y,N,N,N,N,1.370966,103.838202,560108,2125,9.889191
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,...,N,N,N,N,N,1.380709,103.835368,560602,2503,11.008130
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,...,Y,N,N,N,N,1.366201,103.857201,560465,1694,9.274761
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,...,Y,N,Y,N,N,1.381041,103.835132,560601,2181,11.048870

In [9]:
df

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,...,commercial,market_hawker,miscellaneous,multistorey_carpark,precinct_pavilion,LATITUDE,LONGITUDE,POSTAL,time_cbd,Distance_CBD
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,...,N,N,N,N,N,1.362005,103.853880,560406,1919,8.789584
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,...,Y,N,N,N,N,1.370966,103.838202,560108,2125,9.889191
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,...,N,N,N,N,N,1.380709,103.835368,560602,2503,11.008130
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,...,Y,N,N,N,N,1.366201,103.857201,560465,1694,9.274761
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,...,Y,N,Y,N,N,1.381041,103.835132,560601,2181,11.048870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192061,2024-10,YISHUN,5 ROOM,870,YISHUN ST 81,04 TO 06,122.0,Improved,1987,62 years 04 months,...,N,N,N,N,N,1.413074,103.837976,760870,2479,14.539174
192062,2024-10,YISHUN,EXECUTIVE,654,YISHUN AVE 4,10 TO 12,164.0,Apartment,1992,66 years 09 months,...,Y,N,N,N,N,1.423053,103.840410,760654,2645,15.620213
192063,2024-10,YISHUN,EXECUTIVE,654,YISHUN AVE 4,04 TO 06,164.0,Apartment,1992,66 years 09 months,...,Y,N,N,N,N,1.423053,103.840410,760654,2645,15.620213
192064,2024-10,YISHUN,EXECUTIVE,358,YISHUN RING RD,01 TO 03,145.0,Maisonette,1988,62 years 09 months,...,N,N,N,N,N,1.426852,103.845966,760358,2646,16.006595
192065,2024-10,YISHUN,EXECUTIVE,824,YISHUN ST 81,10 TO 12,142.0,Apartment,1987,62 years 02 months,...,N,N,N,N,N,1.413745,103.833303,760824,2329,14.675222

# This portion of the code is to determine the straightline distance to the nearest MRT

In [10]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of Earth in km
    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)
    
    a = np.sin(delta_phi / 2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda / 2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    
    distance = R * c  # Distance in km
    return distance

In [ ]:
# Load the CSV files containing the house and mrt data
mrt = pd.read_csv('mrt.csv')  # Replace with your actual file path


# Convert latitude and longitude to numpy arrays
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
mrt_lats = mrt['Latitude'].values
mrt_lons = mrt['Longitude'].values

# Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
distances_matrix = haversine(
    house_lats[:, np.newaxis], house_lons[:, np.newaxis], 
    mrt_lats, mrt_lons
)

# Find the index of the closest supermarket for each house
closest_indices = np.argmin(distances_matrix, axis=1)

# Get the closest distances for each house
closest_distances = distances_matrix[np.arange(len(df)), closest_indices]

# Add the closest distance to the houses DataFrame
df['Closest_mrt_Distance'] = closest_distances

# Add the name or identifier of the closest MRT station to the houses DataFrame
df['Closest_mrt_Station'] = mrt['Name'].values[closest_indices]

In [ ]:
df

In [ ]:
# Load the CSV files containing the house and busstop data
busstop = pd.read_csv('busstops.csv')  # Replace with your actual file path


# Convert latitude and longitude to numpy arrays
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
busstop_lats = busstop['Latitude'].values
busstop_lons = busstop['Longitude'].values

# Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
# Create a 2D array of school coordinates for KDTree
bus_coors = np.column_stack((busstop_lats, busstop_lons))

# Build a KDTree for schools to efficiently perform range queries
bus_tree = cKDTree(bus_coors)

# Define the distance threshold (1 km)
threshold_distance = 0.5  # in kilometers

# For each house, count how many schools are within 1 km using KDTree
busstop_density = []

for i in range(len(df)):
    house_coord = (house_lats[i], house_lons[i])  # Coordinates of the current house
    
    # Query the KDTree for all schools within the threshold distance
    indices_within_1km = bus_tree.query_ball_point(house_coord, threshold_distance/111.32)
    
    # Append the number of schools within 1 km
    busstop_density.append(len(indices_within_1km))
print(len(busstop_density))
# Add the school density as a new column to the houses DataFrame
df['busstop_Density_Within_1KM'] = busstop_density

# Now df contains the school density within 1km for each house

In [ ]:
df

In [ ]:
# Load the CSV files containing the house and busstop data
hawkercentre = pd.read_csv('hawkercentreloc.csv')  # Replace with your actual file path


# Convert latitude and longitude to numpy arrays
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
hawkercentre_lats = hawkercentre['Latitude'].values
hawkercentre_lons = hawkercentre['Longitude'].values

# Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
distances_matrix = haversine(
    house_lats[:, np.newaxis], house_lons[:, np.newaxis], 
    hawkercentre_lats, hawkercentre_lons
)

# Find the index of the closest supermarket for each house
closest_indices = np.argmin(distances_matrix, axis=1)

# Get the closest distances for each house
closest_distances = distances_matrix[np.arange(len(df)), closest_indices]

# Add the closest distance to the houses DataFrame
df['Closest_hawkercentre_Distance'] = closest_distances

# Add the name or identifier of the closest Hawker to the houses DataFrame
df['Closest_Hawker'] = hawkercentre['Postal Code'].values[closest_indices]

# This portion inserts the distance from each HDB block to CBD.

In [ ]:
# cbd_travel = pd.read_csv("HDB_Distance_To_CBD.csv", index_col =  False)
# cbd_travel = cbd_travel[["block", "street_name", "time_cbd"]]
# df = df.merge(cbd_travel, on=['block', 'street_name'], how='left')

In [ ]:
df

# Mapping Price to Price Index

In [ ]:
price_index = pd.read_csv("MedianPricePerMonth.csv")
df = pd.merge(df, price_index, on=['month'], how='left')

In [ ]:
df

In [ ]:
# Load the CSV files containing the house and mrt data
mrt = pd.read_csv('supermarketloc.csv')  # Replace with your actual file path


# Convert latitude and longitude to numpy arrays
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
mrt_lats = mrt['Latitude'].values
mrt_lons = mrt['Longitude'].values

# Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
distances_matrix = haversine(
    house_lats[:, np.newaxis], house_lons[:, np.newaxis], 
    mrt_lats, mrt_lons
)

# Find the index of the closest supermarket for each house
closest_indices = np.argmin(distances_matrix, axis=1)

# Get the closest distances for each house
closest_distances = distances_matrix[np.arange(len(df)), closest_indices]

# Add the closest distance to the houses DataFrame
df['Closest_supermarket_Distance'] = closest_distances

# Add the name or identifier of the closest MRT station to the houses DataFrame
df['Closest_supermarket_postal'] = mrt['Postal Code'].values[closest_indices]

# This portion of code attempts to find the closest industrial estate to each location

In [ ]:
# Load the CSV files containing the house and mrt data
mrt = pd.read_csv('JTCEstatePoint.csv')  # Replace with your actual file path


# Convert latitude and longitude to numpy arrays
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
mrt_lats = mrt['Latitude'].values
mrt_lons = mrt['Longitude'].values

# Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
distances_matrix = haversine(
    house_lats[:, np.newaxis], house_lons[:, np.newaxis], 
    mrt_lats, mrt_lons
)

# Find the index of the closest supermarket for each house
closest_indices = np.argmin(distances_matrix, axis=1)

# Get the closest distances for each house
closest_distances = distances_matrix[np.arange(len(df)), closest_indices]

# Add the closest distance to the houses DataFrame
df['Closest_industrial_Distance'] = closest_distances

# Add the name or identifier of the closest MRT station to the houses DataFrame
df['Closest_industrial_name'] = mrt['Estate Name'].values[closest_indices]

In [ ]:
schools = pd.read_csv('Generalinformationofschools_lat_long.csv')  # Replace with your actual schools data file path
df_school = schools[schools["mainlevel_code"] == "PRIMARY"]

# Convert latitude and longitude to numpy arrays for houses and schools
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
school_lats = df_school['LATITUDE'].values
school_lons = df_school['LONGITUDE'].values

# Create a 2D array of school coordinates for KDTree
school_coords = np.column_stack((school_lats, school_lons))

# Build a KDTree for schools to efficiently perform range queries
school_tree = cKDTree(school_coords)

# Define the distance threshold (1 km)
threshold_distance = 1.0  # in kilometers

# For each house, count how many schools are within 1 km using KDTree
school_density = []

for i in range(len(df)):
    house_coord = (house_lats[i], house_lons[i])  # Coordinates of the current house
    
    # Query the KDTree for all schools within the threshold distance
    indices_within_1km = school_tree.query_ball_point(house_coord, threshold_distance/111.32)
    
    # Append the number of schools within 1 km
    school_density.append(len(indices_within_1km))

# Add the school density as a new column to the houses DataFrame
df['School_Density_Within_1KM'] = school_density

# Now df contains the school density within 1km for each house

In [ ]:
df

# Investigate the effects of SAP, autonomous, gifted_ind on the price of flats

In [ ]:
special_pri_schools = df_school[(df_school[["sap_ind","autonomous_ind","gifted_ind"]] == "Yes").any(axis=1)]

In [ ]:
special_pri_schools

In [ ]:
# Convert latitude and longitude to numpy arrays for houses and schools
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
school_lats = special_pri_schools['LATITUDE'].values
school_lons = special_pri_schools['LONGITUDE'].values

# Create a 2D array of school coordinates for KDTree
school_coords = np.column_stack((school_lats, school_lons))

# Build a KDTree for schools to efficiently perform range queries
school_tree = cKDTree(school_coords)

# Define the distance threshold (1 km)
threshold_distance = 2.0  # in kilometers

# For each house, count how many schools are within 1 km using KDTree
school_density = []

for i in range(len(df)):
    house_coord = (house_lats[i], house_lons[i])  # Coordinates of the current house
    
    # Query the KDTree for all schools within the threshold distance
    indices_within_1km = school_tree.query_ball_point(house_coord, threshold_distance/111.32)
    
    # Append the number of schools within 1 km
    school_density.append(len(indices_within_1km))

# Add the school density as a new column to the houses DataFrame
df['Special_School_Density_Within_1KM'] = school_density

# Now df contains the school density within 1km for each house

# Estimate the distance to the closest rental flat

In [ ]:
rentalflats = HDB_all_info[(HDB_all_info[["1room_rental","2room_rental","3room_rental","other_room_rental"]]>0).any(axis=1)]

In [ ]:
rentalflats

In [ ]:
# Convert latitude and longitude to numpy arrays for houses and schools
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
rental_lats = rentalflats['LATITUDE'].values
rental_lons = rentalflats['LONGITUDE'].values

#Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
distances_matrix = haversine(
    house_lats[:, np.newaxis], house_lons[:, np.newaxis], 
    rental_lats, rental_lons
)

# Find the index of the closest supermarket for each house
closest_indices = np.argmin(distances_matrix, axis=1)

# Get the closest distances for each house
closest_distances = distances_matrix[np.arange(len(df)), closest_indices]

# Add the closest distance to the houses DataFrame
df['Closest_rental_Distance'] = closest_distances

# This portion of the code determines the latitude and longitude of the shopping malls.

In [ ]:
df_shops = pd.read_csv("shopping_mall_coordinates.csv")

# Convert latitude and longitude to numpy arrays for houses and schools
house_lats = df['LATITUDE'].values
house_lons = df['LONGITUDE'].values
shop_lats = df_shops['LATITUDE'].values
shop_lons = df_shops['LONGITUDE'].values

#Compute the distances between all houses and supermarkets using broadcasting
# We need to calculate distances for every pair of house and supermarket
distances_matrix = haversine(
    house_lats[:, np.newaxis], house_lons[:, np.newaxis], 
    shop_lats, shop_lons
)

# Find the index of the closest supermarket for each house
closest_indices = np.argmin(distances_matrix, axis=1)

# Get the closest distances for each house
closest_distances = distances_matrix[np.arange(len(df)), closest_indices]

# Add the closest distance to the houses DataFrame
df['Closest_Mall_Distance'] = closest_distances

In [ ]:
len(df)

In [ ]:
df = df.dropna()

In [ ]:
len(df)

In [ ]:
df.to_csv("Data_Eng_v7.csv")